### ISSUE TITLE
calibrate_tool not able to access calibration file

### ISSUE THREAD

**Issue by jensanjo** [mangdangroboticsclub/QuadrupedRobot#21]
I have issues with the calibrate tool. At start it gives an error message:

`Error, get nv calibration params failed, use default value. Please calibrate your pupper !`

When I press the 'Update' button I get this error:
```python
out
[[ -9.   9.  12.  15.]
 [ 35.  35.  60.  35.]
 [-30. -27. -22. -48.]]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "calibrate_tool.py", line 239, in updateButton2Event
    self.writeCalibrationFile()
  File "calibrate_tool.py", line 193, in writeCalibrationFile
    with open(ServoCalibrationFilePath, "w") as nv_f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/bus/nvmem/devices/3-00501/nvmem'
``` 
The mentioned path does not exist. Apparently the name is wrong:

```bash
# ls  /sys/bus/nvmem/devices/
3-00500
```
So I changed the path to `/sys/bus/nvmem/devices/3-00500/nvmem` and tried again.
Now it works and there are no error messages

**Comment by mangdangroboticsclub** [comment]
I have not found the issue, could you please let me know your image file name? Thanks!

**Comment by jensanjo** [comment]
I used `20211220_v2.1.3_MiniPupper_V2_PS4_Ubuntu_20.04.2_Baseline.img`

**Comment by mangdangroboticsclub** [comment]
Your version is a little bit old, last year version:)
Please try the 2022 version, such as, 20220109_v1.7.0_MiniPupper_V2_PS4_Ubuntu_21.10.0_Baseline.img.zip , thanks!
https://drive.google.com/drive/folders/17XOR7FHEMkts_zZtZtuQ-QxEJ68U8ZkW

**Comment by jensanjo** [comment]
You closed the issue, but [Ian Nelson](https://www.facebook.com/groups/716473723088464/user/1148280014/)   posted exactly the same issue in the MangdangBackers Facebook group today.
He is using `20220109_v1.7.0_MiniPupper_V2_PS4_Ubuntu_21.10.0_Baseline.img`.
That suggests that the issue is not fixed in the new version.

**Comment by gilaramirez** [comment]
I just ran into the same issue with _20220109_v1.7.0_MiniPupper_V2_PS4_Ubuntu_21.10.0_Baseline.img.zip_ file posted as the solution above.  This bug is not fixed.  Also, I have no directory _/sys/bus/nvmem/devices/3-00500/nvmem_ either.  I'm now trying to flash the software again and check if the file is there at first boot.

I reinstalled fresh and now I have the correct directory and the calibrate tool is working.  I believe the problem is that at one point I had the battery charging but was powering the Raspberry Pi directly from the USB-C port and may have run the calibration tool without power to the mangdang custom card, which somehow erased the file, and the system never rebuilt the directory after the mangdang custom card was powered up.  Let me know if you want me to help isolate the bug.  In the meantime the instructions should be revised to warn not to power the Raspberry Pi directly and try to run the calibration tool.
